version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 17.9.1
    commands:
      - echo "Install phase"
      - npm install
  build:
    commands:
      - echo "Build phase"
      - npm run build
  post_build:
    commands:
      - echo "Post build phase"
      - aws cloudformation package --template-file template.yml --s3-bucket btg-frontend --output-template-file outputtemplate.yml
      - aws cloudformation deploy --template-file outputtemplate.yml --stack-name btg-frontend --capabilities CAPABILITY_IAM
