version 0.2

# buildspec.yml for build spa react app deploy to s3 using aws codebuild & cloudformation
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Install phase"
      - npm install
  build:
    commands:
      - echo "Build phase"
      - npm run build
  post_build:
    commands:
      - echo "Post build phase"
      - aws cloudformation package --template-file template.yml --s3-bucket btg-frontend --output-template-file outputtemplate.yml
      - aws cloudformation deploy --template-file outputtemplate.yml --stack-name btg-frontend --capabilities CAPABILITY_IAM

 Resources:
  ReactAppBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: btg-frontend
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ReactAppBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub 'arn:aws:s3:::btg-frontend-bucket/*'

Outputs:
  WebsiteURL:
    Value: !GetAtt ReactAppBucket.WebsiteURL
    Description: URL for the website hosted on S3
