version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 17.9.1
    commands:
      - echo "Install phase"
      - npm install
  pre_build:
    commands:
      - echo "Pre build phase"
      - >
        export VITE_API_URL=$(aws secretsmanager get-secret-value --secret-id prod/btg-frontend --query SecretString --output text | jq -r '.VITE_API_URL')
  build:
    commands:
      - echo "Build phase"
      - echo "API URL is $VITE_API_URL"
      - npm run build
  post_build:
    commands:
      - echo "Post build phase"
      - aws s3 sync dist/ s3://btg-frontend-bucket --delete
      - aws cloudformation package --template-file template.yaml --s3-bucket btg-frontend --output-template-file outputtemplate.yml
      - aws cloudformation deploy --template-file outputtemplate.yml --stack-name btg-frontend --capabilities CAPABILITY_IAM
