version 0.2

# buildspec.yml for build spa react app deploy to s3 using aws codebuild & cloudformation
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Install phase"
      - npm install
  build:
    commands:
      - echo "Build phase"
      - npm run build
  post_build:
    commands:
      - echo "Post build phase"
      - aws cloudformation package --template-file template.yml --s3-bucket btg-frontend --output-template-file outputtemplate.yml
      - aws cloudformation deploy --template-file outputtemplate.yml --stack-name btg-frontend --capabilities CAPABILITY_IAM