Resources:
  ReactAppBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: btg-frontend
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ReactAppBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "arn:aws:s3:::btg-frontend/*"

Outputs:
  WebsiteURL:
    Value: !GetAtt ReactAppBucket.WebsiteURL
    Description: URL for the website hosted on S3
